name: "Challenger"

main: org.legenddragon.craftattack.craftattack
version: 1.3
api-version: 1.16

author: "LegendDragon11"
description: "Dies ist ein Craftattack Plugin"

permissions:
  server.lock:
    description: "Kann den Server Sperren/Entsperren!"



commands:
  lock:
    aliases: "l"
    description: "Sperrt oder Entsperrt den Server für andere Spieler!"
    usage: "/lock /l"
